"""add_product_table

Revision ID: 2428adcca629
Revises: bcbeb8647a09
Create Date: 2026-02-19 09:52:34.175722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2428adcca629'
down_revision = 'bcbeb8647a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feo_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('product_type', sa.String(length=200), nullable=True),
    sa.Column('is_reusable', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('photo_link', sa.String(length=1000), nullable=True),
    sa.Column('clarification_link', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feo_category_id'], ['feo_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###