"""Справочная таблица переменных для «Руководства по разметке шаблонов».

Вынесено из doc_types.py отдельным файлом ради ограничения ~700 строк на
модуль (204 строки только на этот список) — см. ПРАВИЛО №5."""


# ── Template markup guide ────────────────────────────────────────────────────

TEMPLATE_VARIABLES = [
    # (template_var, description, example_template, example_result)
    # ── Выбор шаблона ──
    ("", "ВЫБОР ШАБЛОНА", "", ""),
    ("", "  contract.docx — универсальный договор (Phase 23.1): subject_kind определяется автоматически.", "", ""),
    ("", "  Все позиции 'услуга' → договор оказания услуг; иначе → договор поставки.", "", ""),
    ("{{subject_kind}}", "Тип договора (auto): вычисляется из позиций закупки", "{{subject_kind}}", "services"),
    # ── Закупка ──
    ("", "ЗАКУПКА", "", ""),
    ("{{purchase_number}}", "Номер закупки", "{{purchase_number}}", "42"),
    ("{{registry_number}}", "Реестровый номер", "{{registry_number}}", "РЕЕ-2026-00042"),
    ("{{subject}}", "Предмет закупки", "{{subject}}", "Оказание услуг связи"),
    ("{{status}}", "Статус", "{{status}}", "contracted"),
    ("{{purchase_method}}", "Способ закупки", "{{purchase_method}}", "Единственный поставщик"),
    ("{{purchase_method_label}}", "Способ закупки (для order_purchase, п.2)", "{{purchase_method_label}}", "Единственный поставщик"),
    ("{{purchase_basis}}", "Основание", "{{purchase_basis}}", "план закупок"),
    ("{{contract_type}}", "Тип договора", "{{contract_type}}", "Единственный поставщик"),
    ("{{responsible_person}}", "ФИО ответственного исполнителя", "{{responsible_person}}", "Иванов Иван Иванович"),
    ("{{feo_category_name}}", "Категория ФЭО (только выбранный узел)", "{{feo_category_name}}", "Услуги связи"),
    ("{{feo_path}}", "Полный путь ФЭО", "{{feo_path}}", "1. Адм → 1.2 IT → 1.2.3 Услуги связи"),
    ("{{feo_level_1}}", "ФЭО уровень 1 — Направление расходов", "{{feo_level_1}}", "1. Административные расходы"),
    ("{{feo_level_2}}", "ФЭО уровень 2 — Тип расходов", "{{feo_level_2}}", "1.2 IT и коммуникации"),
    ("{{feo_level_3}}", "ФЭО уровень 3 — Конкретизированная категория", "{{feo_level_3}}", "1.2.3 Услуги связи"),
    # ── Субсидия и мероприятие ──
    ("", "СУБСИДИЯ И МЕРОПРИЯТИЕ", "", ""),
    ("{{subsidy_name}}", "Наименование субсидии", "{{subsidy_name}}", "ФАДМ-2026"),
    ("{{subsidy_year}}", "Год субсидии", "{{subsidy_year}}", "2026"),
    ("{{subsidy_budget}}", "Бюджет субсидии", "{{subsidy_budget}}", "15 500 000,00 ₽"),
    ("{{event_name}}", "Название мероприятия", "{{event_name}}", "Сборы спасателей"),
    # ── Заказчик (Phase 23) ──
    ("", "ЗАКАЗЧИК", "", ""),
    ("{{customer_name}}", "Краткое название организации Заказчика", "{{customer_name}}", "АНО «ВСКС»"),
    ("{{customer_full_name}}", "Полное наименование", "{{customer_full_name}}", "Автономная некоммерческая организация «ВСКС»"),
    ("{{customer_short_name}}", "Краткое наименование Заказчика (из карточки организации)", "{{customer_short_name}}", "АНО «ВСКС»"),
    ("{{customer_address}}", "Юридический адрес", "{{customer_address}}", "г. Москва, ул. Ленина, д. 1"),
    ("{{customer_postal_address}}", "Почтовый адрес", "{{customer_postal_address}}", "г. Москва, ул. Ленина, д. 1"),
    ("{{customer_inn}}", "ИНН Заказчика", "{{customer_inn}}", "7700000001"),
    ("{{customer_kpp}}", "КПП Заказчика", "{{customer_kpp}}", "770001001"),
    ("{{customer_ogrn}}", "ОГРН Заказчика", "{{customer_ogrn}}", "1027700000001"),
    ("{{customer_bank_name}}", "Банк Заказчика", "{{customer_bank_name}}", "ПАО «Сбербанк»"),
    ("{{customer_settlement_account}}", "Расчётный счёт Заказчика", "{{customer_settlement_account}}", "40703810400000000001"),
    ("{{customer_correspondent_account}}", "Корр. счёт Заказчика", "{{customer_correspondent_account}}", "30101810400000000225"),
    ("{{customer_bik}}", "БИК банка Заказчика", "{{customer_bik}}", "044525225"),
    ("{{customer_phone}}", "Телефон", "{{customer_phone}}", "+7 (495) 000-00-01"),
    ("{{customer_email}}", "Email", "{{customer_email}}", "info@vsks.ru"),
    ("{{customer_signatory}}", "Полная строка подписанта", "{{customer_signatory}}", "Президент Козеев Е.В."),
    ("{{customer_signatory_position}}", "Должность подписанта", "{{customer_signatory_position}}", "Президент"),
    ("{{customer_signatory_name}}", "ФИО подписанта (им.падеж)", "{{customer_signatory_name}}", "Козеев Евгений Викторович"),
    ("{{customer_signatory_name_genitive}}", "ФИО в род.падеже", "{{customer_signatory_name_genitive}}", "Козеева Евгения Викторовича"),
    ("{{customer_signatory_initials}}", "Фамилия + инициалы", "{{customer_signatory_initials}}", "Козеев Е.В."),
    ("{{customer_signatory_basis}}", "Основание полномочий", "{{customer_signatory_basis}}", "Устава"),
    ("{{contract_city}}", "Город заключения договора", "{{contract_city}}", "Москва"),
    # ── Контрагент ──
    ("", "КОНТРАГЕНТ (ИСПОЛНИТЕЛЬ)", "", ""),
    ("{{contractor_name}}", "Полное наименование контрагента", "{{contractor_name}}", "ООО «Ромашка»"),
    ("{{contractor_short_name}}", "Краткое наименование Подрядчика (из карточки контрагента)", "{{contractor_short_name}}", "ООО «Ромашка»"),
    ("{{contractor_org_type}}", "Тип организации", "{{contractor_org_type}}", "Юр.лицо"),
    ("{{contractor_inn}}", "ИНН контрагента", "{{contractor_inn}}", "7701234567"),
    ("{{contractor_kpp}}", "КПП контрагента", "{{contractor_kpp}}", "770101001"),
    ("{{contractor_ogrn}}", "ОГРН / ОГРНИП", "{{contractor_ogrn}}", "1027701234567"),
    ("{{contractor_address}}", "Юридический адрес", "{{contractor_address}}", "г. Москва, ул. Садовая, д. 5"),
    ("{{contractor_postal_address}}", "Почтовый адрес", "{{contractor_postal_address}}", "г. Москва, ул. Садовая, д. 5"),
    ("{{contractor_phone}}", "Телефон", "{{contractor_phone}}", "+7 (495) 111-22-33"),
    ("{{contractor_email}}", "E-mail", "{{contractor_email}}", "info@romashka.ru"),
    ("{{contractor_signatory}}", "ФИО подписанта", "{{contractor_signatory}}", "Сидоров Пётр Павлович"),
    ("{{contractor_signatory_basis}}", "Основание полномочий", "{{contractor_signatory_basis}}", "Устава"),
    ("{{contractor_signatory_position}}", "Должность подписанта", "{{contractor_signatory_position}}", "Директор"),
    ("{{contractor_signatory_name}}", "ФИО в им.падеже", "{{contractor_signatory_name}}", "Сидоров Пётр Павлович"),
    ("{{contractor_signatory_name_genitive}}", "ФИО в род.падеже", "{{contractor_signatory_name_genitive}}", "Сидорова Петра Павловича"),
    ("{{contractor_signatory_initials}}", "Фамилия + инициалы", "{{contractor_signatory_initials}}", "Сидоров П.П."),
    ("{{contractor_signatory_line}}", "ФИО + основание", "{{contractor_signatory_line}}", "Сидоров П.П., действующий на основании Устава"),
    ("{{contractor_ogrnip}}", "ОГРНИП (только для ИП)", "{{contractor_ogrnip}}", "304770000000001"),
    ("{{service_subject}}", "Предмет услуг (синоним subject)", "{{service_subject}}", "Оказание услуг связи"),
    ("{{contractor_settlement_account}}", "Расчётный счёт", "{{contractor_settlement_account}}", "40702810400000000002"),
    ("{{contractor_bank_name}}", "Наименование банка", "{{contractor_bank_name}}", "ПАО «Сбербанк»"),
    ("{{contractor_bank_details}}", "Реквизиты банка", "{{contractor_bank_details}}", "БИК 044525225, к/с 30101810400000000225"),
    ("{{contractor_bik}}", "БИК банка", "{{contractor_bik}}", "044525225"),
    ("{{contractor_correspondent_account}}", "Корреспондентский счёт", "{{contractor_correspondent_account}}", "30101810400000000225"),
    # ── Финансы ──
    ("", "ФИНАНСЫ", "", ""),
    ("{{total_nmcd}}", "НМЦД — начальная максимальная цена договора", "{{total_nmcd}}", "130 000,00 ₽"),
    ("{{total_nmck}}", "НМЦК (устаревшее)", "{{total_nmck}}", "130 000,00 ₽"),
    ("{{nmck}}", "НМЦК (синоним total_nmck)", "{{nmck}}", "130 000,00 ₽"),
    ("{{contract_price}}", "Цена договора", "{{contract_price}}", "130 000,00 ₽"),
    ("{{contract_price_num}}", "Цена без валюты", "{{contract_price_num}}", "130 000,00"),
    ("{{contract_price_words}}", "Цена прописью", "{{contract_price_words}}", "сто тридцать тысяч рублей 00 копеек"),
    ("{{economy}}", "Экономия", "{{economy}}", "5 000,00 ₽"),
    ("{{price_increase}}", "Увеличение цены", "{{price_increase}}", "0,00 ₽"),
    ("{{doc_amount}}", "Сумма закупки для документов (не зависит от стадии: договор → НМЦК/план → сумма позиций)", "{{doc_amount}}", "130 000,00 ₽"),
    ("{{doc_amount_num}}", "Сумма для документов без валюты", "{{doc_amount_num}}", "130 000,00"),
    ("{{doc_amount_words}}", "Сумма для документов прописью", "{{doc_amount_words}}", "сто тридцать тысяч рублей 00 копеек"),
    ("{{amount_is_planned}}", "true, если сумма плановая (договор ещё не заключён)", "{{amount_is_planned}}", "true"),
    ("{{amount_source_label}}", "Подпись источника суммы", "{{amount_source_label}}", "НМЦК (план)"),
    # ── НДС ──
    ("", "НДС", "", ""),
    ("{{vat_applicable}}", "Облагается НДС", "{{vat_applicable}}", "true"),
    ("{{vat_rate}}", "Ставка НДС", "{{vat_rate}}", "20"),
    ("{{vat_amount_num}}", "Сумма НДС цифрами", "{{vat_amount_num}}", "21 666,67"),
    ("{{vat_amount_words}}", "Сумма НДС прописью", "{{vat_amount_words}}", "двадцать одна тысяча 666 руб. 67 коп."),
    ("{{vat_exemption_article}}", "Статья освобождения от НДС", "{{vat_exemption_article}}", "ст. 149 НК РФ"),
    ("{{vat_info_line}}", "Готовая строка НДС", "{{vat_info_line}}", "В том числе НДС 20%: 21 666,67 руб."),
    # ── Договор ──
    ("", "ДОГОВОР", "", ""),
    ("{{contract_number}}", "Номер договора", "{{contract_number}}", "2026/42"),
    ("{{contract_date}}", "Дата договора", "{{contract_date}}", "15.01.2026"),
    ("{{contract_date_day}}", "День", "{{contract_date_day}}", "15"),
    ("{{contract_date_month}}", "Месяц прописью", "{{contract_date_month}}", "января"),
    ("{{contract_date_year}}", "Год", "{{contract_date_year}}", "2026"),
    ("{{execution_term}}", "Срок исполнения", "{{execution_term}}", "28.02.2026"),
    ("{{execution_term_changed}}", "Изменённый срок", "{{execution_term_changed}}", "31.03.2026"),
    ("{{delivery_date}}", "Дата поставки", "{{delivery_date}}", "20.01.2026"),
    ("{{country_origin}}", "Страна происхождения", "{{country_origin}}", "Российская Федерация"),
    ("{{service_name}}", "Предмет (синоним subject)", "{{service_name}}", "Оказание услуг связи"),
    ("{{service_name_gen}}", "Предмет в родительном падеже («Прошу осуществить закупку ...»)", "{{service_name_gen}}", "оказания услуг связи"),
    ("{{period_type}}", "Тип срока", "{{period_type}}", "date"),
    ("{{service_start_date}}", "Начало оказания услуг", "{{service_start_date}}", "15.01.2026"),
    ("{{service_end_date}}", "Конец оказания услуг", "{{service_end_date}}", "28.02.2026"),
    ("{{service_date}}", "Дата оказания (разовая)", "{{service_date}}", "20.01.2026"),
    ("{{third_party_involved}}", "Привлечение третьих лиц", "{{third_party_involved}}", "false"),
    # ── Phase 19: срок услуг расширенный ──
    ("", "СРОК УСЛУГ (Phase 19)", "", ""),
    ("{{service_term}}", "Готовая строка срока", "{{service_term}}", "с 15.01.2026 по 28.02.2026"),
    ("{{service_term_mode}}", "Режим срока", "{{service_term_mode}}", "range"),
    ("{{service_term_days}}", "Кол-во дней (для mode=duration)", "{{service_term_days}}", "30"),
    ("{{service_term_type}}", "Тип дней", "{{service_term_type}}", "calendar"),
    ("{{service_term_type_name}}", "Тип дней прописью", "{{service_term_type_name}}", "календарных"),
    ("{{service_deadline_date}}", "Срок \"до даты\"", "{{service_deadline_date}}", "28.02.2026"),
    # ── Phase 19: приём заявок ──
    ("", "ПРИЁМ ЗАЯВОК (Phase 19)", "", ""),
    ("{{submission_deadline_date}}", "Дата завершения приёма заявок", "{{submission_deadline_date}}", "10.01.2026"),
    ("{{submission_deadline_time}}", "Время завершения приёма заявок", "{{submission_deadline_time}}", "17:00"),
    ("{{submission_deadline_datetime}}", "Дата+время завершения", "{{submission_deadline_datetime}}", "10.01.2026 17:00"),
    # ── Phase 19: место доставки ──
    ("", "МЕСТО ДОСТАВКИ / ОКАЗАНИЯ УСЛУГ (Phase 19)", "", ""),
    ("{{delivery_location}}", "Место оказания услуг / доставки", "{{delivery_location}}", "г. Москва, ул. Ленина, д. 1"),
    # ── Phase 19: соглашение субсидии ──
    ("", "СОГЛАШЕНИЕ ПО СУБСИДИИ (Phase 19)", "", ""),
    ("{{subsidy_agreement_text}}", "Большой текст соглашения", "{{subsidy_agreement_text}}", "(многострочный текст)"),
    # ── Акт приёмки ──
    ("", "АКТ ПРИЁМКИ", "", ""),
    ("{{acceptance_doc_name}}", "Наименование акта", "{{acceptance_doc_name}}", "АКТ"),
    ("{{acceptance_doc_number}}", "Номер акта", "{{acceptance_doc_number}}", "001"),
    ("{{acceptance_doc_date}}", "Дата акта", "{{acceptance_doc_date}}", "28.02.2026"),
    ("{{acceptance_doc_amount}}", "Сумма акта", "{{acceptance_doc_amount}}", "130 000,00"),
    # ── Платёж ──
    ("", "ПЛАТЁЖ", "", ""),
    ("{{payment_doc_number}}", "Номер платёжного поручения", "{{payment_doc_number}}", "П-00125"),
    ("{{payment_doc_date}}", "Дата ПП", "{{payment_doc_date}}", "05.03.2026"),
    ("{{payment_amount}}", "Сумма платежа", "{{payment_amount}}", "130 000,00"),
    ("{{payment_federal}}", "В т.ч. федеральный бюджет", "{{payment_federal}}", "100 000,00"),
    # ── Инициатор ──
    ("", "ИНИЦИАТОР (для служебных записок)", "", ""),
    ("{{initiator_name}}", "ФИО инициатора", "{{initiator_name}}", "Иванов И.И."),
    ("{{initiator_role}}", "Должность инициатора", "{{initiator_role}}", "начальник отдела"),
    ("{{initiator_dept}}", "Отдел инициатора (если несколько — первый)", "{{initiator_dept}}", "Отдел спасательных операций"),
    # ── Согласующие (цикл) ──
    ("", "СОГЛАСУЮЩИЕ (цикл для таблицы)", "", ""),
    ("{%tr for a in approvers %} ... {%tr endfor %}", "Цикл по согласующим (в строке таблицы)", "{%tr for a in approvers %}<строка>{%tr endfor %}", "повторяется по числу согласующих"),
    ("{{a.num}}", "Порядковый номер (1, 2, 3...)", "{{a.num}}", "1"),
    ("{{a.role_name}}", "Должность согласующего", "{{a.role_name}}", "начальник отдела"),
    ("{{a.full_name}}", "ФИО согласующего (сокращённо: Фамилия И.О.)", "{{a.full_name}}", "Петров П.П."),
    ("{{a.full_name_full}}", "ФИО согласующего целиком, без сокращения", "{{a.full_name_full}}", "Петров Пётр Петрович"),
    ("{{a.signature_img}}", "Электронная подпись (картинка)", "{{a.signature_img}}", "(изображение подписи)"),
    ("{{a.decided_date}}", "Дата подписания", "{{a.decided_date}}", "12.05.2026"),
    ("{{a.note}}", "Примечание (путь ФЭО)", "{{a.note}}", "Согласовано"),
    # ── Позиции (цикл) ──
    ("", "ПОЗИЦИИ ЗАКУПКИ (цикл для таблицы)", "", ""),
    ("{%tr for item in items %} ... {%tr endfor %}", "Цикл по позициям (в строке таблицы)", "{%tr for item in items %}<строка>{%tr endfor %}", "повторяется по числу позиций"),
    ("{{item.num}}", "Порядковый номер", "{{item.num}}", "1"),
    ("{{item.name}}", "Наименование товара/услуги", "{{item.name}}", "Услуги мобильной связи"),
    ("{{item.description}}", "Описание (из карточки продукта)", "{{item.description}}", "Корпоративная SIM-карта"),
    ("{{item.type}}", "Тип (товар/услуга)", "{{item.type}}", "услуга"),
    ("{{item.quantity}}", "Количество", "{{item.quantity}}", "10"),
    ("{{item.unit}}", "Единица измерения", "{{item.unit}}", "шт."),
    ("{{item.unit_price}}", "Цена за единицу", "{{item.unit_price}}", "13 000,00"),
    ("{{item.total_price}}", "Сумма строки", "{{item.total_price}}", "130 000,00"),
    ("{{item.photo}}", "Фото товара (картинка)", "{{item.photo}}", "(изображение)"),
    ("{{items_count}}", "Общее количество позиций", "{{items_count}}", "3"),
    ("{{item_names}}", "Перечень названий через запятую", "{{item_names}}", "Услуги связи, Интернет, Хостинг"),
    # ── Чеки (авансовый отчёт) ──
    ("", "ЧЕКИ — АВАНСОВЫЙ ОТЧЁТ (только для закупок с purchase_method=advance)", "", ""),
    ("{{receipts}}", "Список InlineImage чеков (ширина 6.5 см) — стандартная колонка", "{% for r in receipts %}{{ r }}{% endfor %}", "(изображения чеков 6.5 см)"),
    ("{{receipt_images}}", "Алиас receipts — список изображений чеков 6.5 см", "{% for img in receipt_images %}{{ img }}{% endfor %}", "(изображения чеков 6.5 см)"),
    ("{{receipts_small}}", "Чеки 4.5 см — для узких ячеек 2-колоночных таблиц", "{% for r in receipts_small %}{{ r }}{% endfor %}", "(маленькие чеки 4.5 см)"),
    ("{{receipts_full}}", "Чеки 14 см — для full-width страниц (один чек на страницу)", "{% for r in receipts_full %}{{ r }}{% endfor %}", "(полноширинные чеки 14 см)"),
    ("{{left_receipts}}", "Чёткые позиции чеков 4.5 см (1-й, 3-й, ...) — левая колонка таблицы 1×2", "{% for r in left_receipts %}{{ r }}{% endfor %}", "(чеки 1,3,5...)"),
    ("{{right_receipts}}", "Нечёткие позиции чеков 4.5 см (2-й, 4-й, ...) — правая колонка таблицы 1×2", "{% for r in right_receipts %}{{ r }}{% endfor %}", "(чеки 2,4,6...)"),
    # ── Родительный падеж (Phase 26-V) ──
    ("", "РОДИТЕЛЬНЫЙ ПАДЕЖ (Phase 26-V)", "", ""),
    ("{{initiator_name_gen}}", "ФИО инициатора в родительном падеже", "{{initiator_name_gen}}", "Иванова И.И."),
    ("{{initiator_position_gen}}", "Должность инициатора в родительном падеже", "{{initiator_position_gen}}", "начальника отдела"),
    ("{{initiator_dept_gen}}", "Отдел инициатора в родительном падеже (с авто-удалением дубля «Отдел» если он уже есть в должности)", "{{initiator_dept_gen}}", "мто"),
    ("{{responsible_name_gen}}", "ФИО ответственного в родительном падеже", "{{responsible_name_gen}}", "Петрова П.П."),
    ("{{responsible_position_gen}}", "Должность ответственного в родительном падеже", "{{responsible_position_gen}}", "главного специалиста"),
    ("{{a.full_name_gen}}", "ФИО согласующего в родительном падеже (внутри цикла)", "{{a.full_name_gen}}", "Сидорова С.С."),
    ("{{a.role_name_gen}}", "Должность согласующего в родительном падеже (внутри цикла)", "{{a.role_name_gen}}", "директора по правовым вопросам"),
    # ── Служебные ──
    ("", "СЛУЖЕБНЫЕ", "", ""),
    ("{{today}}", "Сегодняшняя дата", "{{today}}", "13.05.2026"),
    ("{{today_iso}}", "Дата ISO", "{{today_iso}}", "2026-05-13"),
]
