"""Facade module: re-exports all pydantic schemas.

Historically all schemas lived in this single file. They have been split into
domain modules under app/schemas/ (auth, subsidies, contracts, purchases,
payments, products, marketplace, tasks, feo, permissions, reports) to keep
files under ~700 lines (правило №5). This module re-exports every public name
so existing `from app.schemas.schemas import X` call sites keep working
unchanged.
"""
import re
from pydantic import BaseModel, ConfigDict, Field, model_validator, field_validator
from typing import Optional, List, Any, Dict, Literal
from datetime import date, datetime
from decimal import Decimal

from .auth import (
    LoginRequest,
    Token,
    UserCreate,
    UserUpdate,
    PermissionsOut,
    UserOut,
    OrganizationCreate,
    OrganizationOut,
    RegisterRequest,
)
from .subsidies import (
    SubsidyCreate,
    SubsidyUpdate,
    SubsidyOut,
    SubsidyContractorOverrideCreate,
    SubsidyContractorOverrideOut,
    ResponsiblePersonCreate,
    ResponsiblePersonOut,
    SubsidyApproverCreate,
    SubsidyApproverOut,
    FeoCategoryCreate,
    FeoCategoryOut,
    FeoCategoryTree,
)
from .contracts import (
    ContractorCreate,
    ContractorOut,
    ContractSubsidyOut,
    ContractCreate,
    ContractOut,
    ContractSyncWarnings,
    ContractUpdateResponse,
    ContractItemBase,
    ContractItemCreate,
    ContractItemUpdate,
    ContractItemOut,
)
from .purchases import (
    PurchaseItemCreate,
    PurchaseItemOut,
    PurchaseFileOut,
    SubsidyAllocationIn,
    SubsidyAllocationOut,
    PurchaseCreate,
    PurchaseUpdate,
    FeoMismatchItemOut,
    PurchaseOut,
    PurchaseAmountsOut,
    PurchaseOutFull,
)
from .payments import (
    PaymentCreate,
    PaymentOut,
    ReceiptItemIn,
    ReceiptCreate,
    ReceiptOut,
    BankStatementImportOut,
    BankPaymentOut,
    BankPaymentMatchUpdate,
    BankPaymentConfirm,
)
from .products import (
    PriceLink,
    PriceFreshnessOut,
    ProductCreate,
    ProductOut,
    PriceActualizationIn,
    ProductPriceHistoryOut,
    ProductSummaryItem,
    ProductSummaryGroup,
    DashboardCategory,
    DashboardSummary,
)
from .marketplace import (
    PlatformCredentialUpsert,
    PlatformCredentialOut,
    PublishRequest,
    PublicationStatusUpdate,
    PublicationOut,
    CommercialRequestRecipientOut,
    FreeRecipient,
    CommercialRequestCreate,
    CommercialRequestUpdate,
    CommercialRequestStatusUpdate,
    CommercialRequestRecipientStatusUpdate,
    CommercialRequestOut,
    CommercialRequestOfferIn,
    CommercialRequestOfferOut,
    SupplierProductOut,
    SupplierCreate,
    SupplierOut,
    SupplierProductCreate,
)
from .tasks import (
    EventCreate,
    EventOut,
    PurchaseApprovalOut,
    ApprovalDecisionRequest,
    TaskAssigneeOut,
    TaskCreate,
    TaskUpdate,
    ReviewCompleteRequest,
    TaskOut,
    DismissFieldRequest,
    TaskCommentCreate,
    TaskCommentOut,
)
from .feo import (
    FeoPlannedItemCreate,
    FeoPlannedItemOut,
    FeoPlannedItemBulkCreate,
    FeoPlannedItemBulkCreateResult,
    FeoStageOut,
    FeoActualItemOut,
    FeoComparisonOut,
    BudgetHistoryItemOut,
)
from .permissions import (
    PermissionTabOut,
    PermissionActionOut,
    RolePermissionOut,
    RoleMatrixRow,
    PermissionUpdate,
    RoleUpdate,
    OverrideOut,
)
from .reports import (
    ReportConfigCreate,
    ReportConfigUpdate,
    ReportConfigOut,
)

__all__ = [
    "LoginRequest",
    "Token",
    "UserCreate",
    "UserUpdate",
    "PermissionsOut",
    "UserOut",
    "OrganizationCreate",
    "OrganizationOut",
    "RegisterRequest",
    "SubsidyCreate",
    "SubsidyUpdate",
    "SubsidyOut",
    "SubsidyContractorOverrideCreate",
    "SubsidyContractorOverrideOut",
    "ResponsiblePersonCreate",
    "ResponsiblePersonOut",
    "SubsidyApproverCreate",
    "SubsidyApproverOut",
    "FeoCategoryCreate",
    "FeoCategoryOut",
    "FeoCategoryTree",
    "ContractorCreate",
    "ContractorOut",
    "ContractSubsidyOut",
    "ContractCreate",
    "ContractOut",
    "ContractSyncWarnings",
    "ContractUpdateResponse",
    "ContractItemBase",
    "ContractItemCreate",
    "ContractItemUpdate",
    "ContractItemOut",
    "PurchaseItemCreate",
    "PurchaseItemOut",
    "PurchaseFileOut",
    "SubsidyAllocationIn",
    "SubsidyAllocationOut",
    "PurchaseCreate",
    "PurchaseUpdate",
    "FeoMismatchItemOut",
    "PurchaseOut",
    "PurchaseAmountsOut",
    "PurchaseOutFull",
    "PaymentCreate",
    "PaymentOut",
    "ReceiptItemIn",
    "ReceiptCreate",
    "ReceiptOut",
    "BankStatementImportOut",
    "BankPaymentOut",
    "BankPaymentMatchUpdate",
    "BankPaymentConfirm",
    "PriceLink",
    "PriceFreshnessOut",
    "ProductCreate",
    "ProductOut",
    "PriceActualizationIn",
    "ProductPriceHistoryOut",
    "ProductSummaryItem",
    "ProductSummaryGroup",
    "DashboardCategory",
    "DashboardSummary",
    "PlatformCredentialUpsert",
    "PlatformCredentialOut",
    "PublishRequest",
    "PublicationStatusUpdate",
    "PublicationOut",
    "CommercialRequestRecipientOut",
    "FreeRecipient",
    "CommercialRequestCreate",
    "CommercialRequestUpdate",
    "CommercialRequestStatusUpdate",
    "CommercialRequestRecipientStatusUpdate",
    "CommercialRequestOut",
    "CommercialRequestOfferIn",
    "CommercialRequestOfferOut",
    "SupplierProductOut",
    "SupplierCreate",
    "SupplierOut",
    "SupplierProductCreate",
    "EventCreate",
    "EventOut",
    "PurchaseApprovalOut",
    "ApprovalDecisionRequest",
    "TaskAssigneeOut",
    "TaskCreate",
    "TaskUpdate",
    "ReviewCompleteRequest",
    "TaskOut",
    "DismissFieldRequest",
    "TaskCommentCreate",
    "TaskCommentOut",
    "FeoPlannedItemCreate",
    "FeoPlannedItemOut",
    "FeoPlannedItemBulkCreate",
    "FeoPlannedItemBulkCreateResult",
    "FeoStageOut",
    "FeoActualItemOut",
    "FeoComparisonOut",
    "BudgetHistoryItemOut",
    "PermissionTabOut",
    "PermissionActionOut",
    "RolePermissionOut",
    "RoleMatrixRow",
    "PermissionUpdate",
    "RoleUpdate",
    "OverrideOut",
    "ReportConfigCreate",
    "ReportConfigUpdate",
    "ReportConfigOut",
]

# Preserve pre-split introspection identity: each schema class now physically
# lives in a domain submodule, but code (and FastAPI's OpenAPI component
# naming, which disambiguates same-named classes via __module__) previously
# saw them all as defined in app.schemas.schemas. Re-stamp __module__ so
# behavior/output is unchanged for external inspectors (e.g. a same-named but
# unrelated EventOut in app/routers/purchase_events.py otherwise causes
# FastAPI to rename components using each class's real submodule).
for _name in __all__:
    globals()[_name].__module__ = __name__
del _name
